spring:
  application:
    name: angularbackend
  datasource:
    url: jdbc:mysql://localhost:3306/angularbackend?createDatabaseIfNotExist=true
    username: root
    password: mypassword1
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}
    accessTokenExpiration: 300 # 5 min
    refreshTokenExpiration: 604800 # 7 days