spring:
  application:
    name: angularbackend
  datasource:
    url: jdbc:mysql://localhost:3306/angularbackend?createDatabaseIfNotExist=true
    username: root
    password: mypassword1
  jpa:
    show-sql: true
  jwt:
    secret: ${JWT_SECRET}