spring:
  datasource:
    url: jdbc:mysql://localhost:3306/angularbackend?createDatabaseIfNotExist=true
    username: root
    password: mypassword1
  jpa:
    show-sql: true
websiteUrl: http://localhost:4242